// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqyiinliamrgljniojgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxeWlpbmxpYW1yZ2xqbmlvamd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjQ1OTMsImV4cCI6MjA2MzAwMDU5M30.mdrz-5kuen-E3bW8V6-Ren3qQneXURHyVdY3VM4qvzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);